
   
name: Create Report
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron: "0 0 * * *" 
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install library and other requirements
      run: |
        pip install jupyter nbconvert
        pip install -r requirements.txt 
    - name: Grab Needed Data
      run: |
         wget https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-{2002..2021}.json.zip 
         unzip -o "*.zip" 
    - name: Run Notebooks
      env:
        GH_TOKEN:  ${{ secrets.GH_TOKEN }}
      run: |
         # jupyter nbconvert --to notebook --execute 2021.ipynb
         # jupyter nbconvert --to html --TemplateExporter.exclude_input=True --no-prompt 2021.nbconvert.ipynb --output 2021.html
         jupyter nbconvert --to notebook --execute cveicu.ipynb
         jupyter nbconvert --to html --TemplateExporter.exclude_input=True --no-prompt cveicu.nbconvert.ipynb --output index.html
         sed -i 's/cveicu.nbconvert/cve.icu/g' index.html
         mv *.html docs/
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Jerry Gamblin
        message: "Update CVE Reports"
        add: "."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
